### ISSUE TITLE
Supporting linux/arm64

### ISSUE THREAD

**Issue by chhsiao1981** [bbsdocker/imageptt#5]
Both linux/arm64 and mac can be beneficial from this support.

The caveat to have arm64 is that the openresty repo is a little bit different.
(amd64: https://openresty.org/package/debian
 arm64: https://openresty.org/package/arm64/debian)

We can achieve supporting linux/arm64 with the following steps:

1. adding ARG OPENRESTY_PLATFORM=
2. have a separated `.github/workflows/push_container_arm64.yml`

**Comment by holishing** [comment]
todo: (for me)
1. split tags to different arch (amd64/arm64)
2. confirm latest package dependencies change in debian side.

**Comment by chhsiao1981** [comment]
> todo: (for me)
> 
> 1. split tags to different arch (amd64/arm64)
> 2. confirm latest package dependencies change in debian side.


@holishing 

hmm～
I thought it was listed as both accessible with different arch 
(like [node](https://hub.docker.com/_/node/tags)) but [now only arm64 appears](https://hub.docker.com/r/bbsdocker/imageptt/tags).

Perhaps it's because we build from different OPENRESTY_ARCH.

**Comment by chhsiao1981** [comment]
Perhaps we can change FROM image to openresty.

https://hub.docker.com/r/openresty/openresty/tags

The only concern with the openresty image
is that it may include something we dont want to include.

Another option is to have arm64 postfix in the tag.
